### ISSUE TITLE
doesn't work on Java 9

### ISSUE THREAD

**Issue by smack42** [neophob/appstart#1]
This application starter doesn't work any more on Java 9 and current Java 10 platforms. The error message is:
```
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
```

Apparently this is caused by a change that was part of Java 9:
http://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html
> The application class loader is no longer an instance of java.net.URLClassLoader (an implementation detail that was never specified in previous releases). Code that assumes that ClassLoader::getSytemClassLoader returns a URLClassLoader object will need to be updated. Note that Java SE and the JDK do not provide an API for applications or libraries to dynamically augment the class path at run-time.

I'm using this application starter in one of my projects https://github.com/smack42/DriftingDroids.
I would be happy if you'd be interested in working on a solution to this problem.

**Comment by neophob** [comment]
thanks for the report, but currently I do not use this anymore. feel free to fork and fix it ;)
