### ISSUE TITLE
works great but not acceptable to the app store

### ISSUE THREAD

**Issue by ddyer0** [neophob/appstart#3]
It works (on your desktop) to substitute universalJavaApplicationStub for the JavaApplicationLauncher,
but the resulting app is not acceptable to the app store.  Transporter fails with ITMS-90085, complaining
about needing a valid CFBundleExecutable property.

My guess is that this is because the stub script can't be signed.  Some kind of wrapper is needed.

**Comment by neophob** [comment]
yeah, 7 years ago that was not a thing ;) I don't active maintain this library anymore, feel free to fork and fix it.

**Comment by ddyer0** [comment]
There are a bunch of them already - and now there's "jpackage" which
seems to be an official effort to provide the functionality.
